services:
  - type: web
    name: wordpress
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: WORDPRESS_DB_HOST
        fromDatabase:
          name: wordpress-db
          property: host
      - key: WORDPRESS_DB_USER
        fromDatabase:
          name: wordpress-db
          property: user
      - key: WORDPRESS_DB_PASSWORD
        fromDatabase:
          name: wordpress-db
          property: password
      - key: WORDPRESS_DB_NAME
        fromDatabase:
          name: wordpress-db
          property: database
